apiVersion: v1
kind: ConfigMap
metadata:
  name: halkyon-nginx-config
data:
  server-block.conf: |-
    server {
      listen            0.0.0.0:8080;
      root              /app;
      location ~ "(/[^/]+/[^/]+)(/.*)?" {
          if ($arg_go-get = "1") {
             echo '<html><head><meta name="go-import" content="halkyon.io$1 git git+ssh://git@my.domain.com$1"/></head></html>';
          }
          try_files $uri $uri/index.html $uri.html @git;
      }
    }