apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: halkyon-nginx
spec:
  host: halkyon.io
  tls:
    certificate: |-
      -----BEGIN CERTIFICATE-----
      MIIFSzCCBDOgAwIBAgISA9LwhWi/JPxlSVSXZYi4tHYFMA0GCSqGSIb3DQEBCwUA
      MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
      ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xOTA4MTMxNDI2NDVaFw0x
      OTExMTExNDI2NDVaMBUxEzARBgNVBAMTCmhhbGt5b24uaW8wggEiMA0GCSqGSIb3
      DQEBAQUAA4IBDwAwggEKAoIBAQDN04lHfT5X1mFVxEvr7Y3n1J4Rm0xpwuEWqPB3
      Cd9C+94I8LAekXmGZfrl4nXEf8evVLN74+4w1teAuuGYFgs51jxy7IxIhwDy3EG2
      ixffbkWVyFdBwOSDy8iWx7qSajdsrQgYflCgB1TkLZ360EwN12gW/8cLd1b7b3Gq
      vzfEaiwhWWJ+jyolUH5lN4r3UK1BHFm06LjDUTph12+c0VPdF/4bnLHTpBmwSeKJ
      Iy8t+QGhLxOzT57MFO0ob4l9zHwpbl+tQxNkBwSy1IzBtg7alMPBw8QGTT0XbMTe
      QKLeNq/JmcozIydoaZMArOZPuFypYq6i/kBdYJkTyFucob51AgMBAAGjggJeMIIC
      WjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
      MAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFNgbJeYTnW0Pt5ssAkSdhARnAIUmMB8G
      A1UdIwQYMBaAFKhKamMEfd265tE5t6ZFZe/zqOyhMG8GCCsGAQUFBwEBBGMwYTAu
      BggrBgEFBQcwAYYiaHR0cDovL29jc3AuaW50LXgzLmxldHNlbmNyeXB0Lm9yZzAv
      BggrBgEFBQcwAoYjaHR0cDovL2NlcnQuaW50LXgzLmxldHNlbmNyeXB0Lm9yZy8w
      FQYDVR0RBA4wDIIKaGFsa3lvbi5pbzBMBgNVHSAERTBDMAgGBmeBDAECATA3Bgsr
      BgEEAYLfEwEBATAoMCYGCCsGAQUFBwIBFhpodHRwOi8vY3BzLmxldHNlbmNyeXB0
      Lm9yZzCCAQMGCisGAQQB1nkCBAIEgfQEgfEA7wB2AOJpS64m6OlACeiGG7Y7g9Q+
      5/50iPukjyiTAZ3d8dv+AAABbIuWs5gAAAQDAEcwRQIgMMQ35Sj5gdegzE0JdSos
      OhgBzSECbIgazqwUJ/p7QiECIQD8810E+OPba/rHR2MvhlenpjV8w+KOt7SNQLK4
      y+dppwB1ACk8UZZUyDlluqpQ/FgH1Ldvv1h6KXLcpMMM9OVFR/R4AAABbIuWs7kA
      AAQDAEYwRAIgGjGfn/R4kwdozV/bqTuGR9lgyISswoX/E07brzNKLIUCIFY8CABC
      ZycOqjAflFQqaA7dBjdcCG++KW+dK+Qivkn3MA0GCSqGSIb3DQEBCwUAA4IBAQA9
      daACVVZXedil66LMjmySbAVq+B25lkBieO+XEhLeS3QnlPAbXuDckaSjbykIghdH
      2eXp4a/UL2XZoMLNfIxEpXxTy22jmY5mVY+Bh0oJRa8IpxR/dJpEp9hJRkKoJPj3
      CjUPaMlaC3gNy5aTe/73RPoGDKEvzM9ydK9D1eZj1/0TT0g3O06aFfY++kGfoKk5
      rxtK32WJr6GTaXZ+zukST4U6BaflP7UdmcbYldDzQjDkh6/UVs26VTv4n/XN1iQx
      C6VyfDeIQ+No84ZTI/7ZKZnm1W99X+oy+qYn8azorDUrpH4g1673JgMni7KgTUWC
      of2RdOGXPMs+5N5J6IeW
      -----END CERTIFICATE-----
    caCertificate: |-
      -----BEGIN CERTIFICATE-----
      MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
      MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
      DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow
      SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT
      GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC
      AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF
      q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8
      SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0
      Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA
      a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj
      /PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T
      AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG
      CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv
      bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k
      c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw
      VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC
      ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz
      MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu
      Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF
      AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo
      uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/
      wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu
      X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG
      PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
      KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAzdOJR30+V9ZhVcRL6+2N59SeEZtMacLhFqjwdwnfQvveCPCw
      HpF5hmX65eJ1xH/Hr1Sze+PuMNbXgLrhmBYLOdY8cuyMSIcA8txBtosX325FlchX
      QcDkg8vIlse6kmo3bK0IGH5QoAdU5C2d+tBMDddoFv/HC3dW+29xqr83xGosIVli
      fo8qJVB+ZTeK91CtQRxZtOi4w1E6YddvnNFT3Rf+G5yx06QZsEniiSMvLfkBoS8T
      s0+ezBTtKG+Jfcx8KW5frUMTZAcEstSMwbYO2pTDwcPEBk09F2zE3kCi3javyZnK
      MyMnaGmTAKzmT7hcqWKuov5AXWCZE8hbnKG+dQIDAQABAoIBAAf2Ib5BKvMs2LD/
      mcwzcSTBhae6sRb6Mci1mi+QkzE9GtaPsNBN4jx/n1fbDaEfLDMs/JBTPbhn5wgU
      sns2hxKipc3wNnDrv+6k9GnCMZcz5b8oc6+YbX5nmIe0jBPzxdcPTlvcLvQxtGfr
      F8xG2FpEtcMF+8YGxLePFP98zARt4SSdf7yd4fOD9Fyu3z8pwGMy+N9mlYMaL5UV
      LEfzgWks3oLv2U92snUdmCwfj9PqX9d3Aq05BpE3UZrPwQoOPjhry/0OGwmlJl0H
      i+MFadEvfpHHNj6fxoQ3xP5zq9+fvi60j4rxdWe+w4jyY8GxiOeHsUChlTISeNGi
      EVvnC3UCgYEA8g7v65JH8xo5DSFIpAP8ANN+oBOi38uFAFhBDQmBo7lfoU4KITzP
      lVoXDIMw5suilsOtE4V38nxXOfMMcpRVoG1pu0KQR//5s6NF9dT8aJHLhmPFeVQY
      qaKgR4iiFcFLmfYkLtzHfWVEQeGvJ/OMt/vgcGM9XQ5vFAUlJj1cQCsCgYEA2a5e
      7SqGLExwbHRiCJNLBjW8A4OjRMB84ib/xyUoKndO9u1yoND/V9IaeCJzjM336zwl
      lYOcHMkjT2vISvBnYSvO4FEJ1dFM1gqeJl5nxB2iLsww/AtfyK04n9lwq66UQbWx
      xP5mIakMjAZ1iwz3xufRig6W/wNweGxdOdGMC98CgYBH/E05f31KPMgusXFK5axy
      CnOj43MSnxHkslpWKDeXmy9nZy/4Bn+taOdl3zYRzQmDUJoOLiknwfam0zMmeBqm
      5SMGf5ss7mEyHSJXI4oVBxbB1rYJiQr0l9qWq3mYgq2bEepczWe+UPllplpSxUla
      BdwPUFQVco9yIr2Ti7f9lQKBgQCnegbCxbLRJkZgyvIZ0ukn7/OlaIQXA1mRzZuA
      pk/OzFhOlsVYgTPTZ2zB/Q+Vx2n07COmcsmLRB0Mn8pMDcYb9s6FuxOsFAnfq++d
      aYjAVGRRSPxvDnk1NkCYi3yqOfkKzTXmcCw3vY5PtTB+OQ3xVK3cX/lAXm8L16Oq
      NlRfVQKBgENWo51snNQLaTDVdGIxBZdAdap/4g23enHKzp1sV6c42N4tUTASV70a
      CHEIZ37Lk8o0psMW/oIKnzYK1r7IGY1rXBv2ZvdGnN1hbuimwPZy3Un08ZNciiWc
      IYKxdNQqoODv5HCGc+AlvOGzYUyvJLThI5XHseVKQ0mRPTdyxHdZ
      -----END RSA PRIVATE KEY-----
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: halkyon-nginx
    weight: 100
  wildcardPolicy: None
