apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  name: halkyon-nginx
spec:
  rules:
    - host: halkyon.io
      http:
        paths:
          - backend:
              serviceName: halkyon-nginx
              servicePort: 80
            path: /
  tls:
    - hosts:
        - halkyon.io
        - www.halkyon.io
      secretName: www-halkyon-io-tls